apiVersion: v1
kind: Service
metadata:
  name: kube2py-service
  namespace: my-namespace
spec:
  selector:
    app: todolist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP